# Site setting
name: Eric
email: 13021999163@163.com
author: Zhao Libin
url: http://www.zhaolibin.com
resume_site: http://www.zhaolibin.com/Resume.io/
github: https://github.com/zhaolibingit/
baseurl: ""
description: Just do it !!!
meta_description: 赵历斌;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: zhaolibingit

# Build settings
markdown: kramdown

baidu_analysis: 7d8b12e46dce32ebc1e02078e54067c7
revolvermaps: 5lv6zj452u8